name: packer-res0nat0r
version: 1.2.2
summary: Packer - Build Automated Machine Images
description: |
  HashiCorp Packer is easy to use and automates the creation of any type of
  machine image. It embraces modern configuration management by encouraging
  you to use automated scripts to install and configure the software within
  your Packer-made images. Packer brings machine images into the modern age,
  unlocking untapped potential and opening new opportunities. 
type: app
grade: stable
architectures: [amd64]
confinement: strict

apps:
  packer:
    command: packer
    plugs:
      - network
      - home

parts:
  packer:
    plugin: dump
    source: https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
    source-checksum: sha256/d86e2236208e8efb7e9a4e788072b428de3f2300414cb338cf1836e0985666e0
    organize:
      packer: bin/packer
